### ISSUE TITLE
if the cors is not enabled on ovirt-engine, no error on cockpit

### ISSUE THREAD

**Issue by jelkosz** [oVirt/cockpit-machines-ovirt-provider#13]
only the console contains a warning:
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://<addr>/ovirt-engine/api/hosts. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).  (unknown)

**Comment by jelkosz** [comment]
similar to this, same if you have mixed content:
Loading mixed (insecure) active content “http:/<addr>/ovirt-engine/api/hosts” on a secure page[Learn More]

**Comment by sandrobonazzola** [comment]
This project has been migrated under Cockpit, became base for cockpit-machines-provider.

This source base is no more maintained.
