### ISSUE TITLE
incorrectly aligned "oVirt authentication in progress ..."

### ISSUE THREAD

**Issue by jelkosz** [oVirt/cockpit-machines-ovirt-provider#18]
The loading icon and the text seems misplaced.

![cocpit-loading](https://cloud.githubusercontent.com/assets/701107/24711198/8e20c302-1a1f-11e7-8dbf-25276eeaa55d.png)

**Comment by sandrobonazzola** [comment]
This project has been migrated under Cockpit, became base for cockpit-machines-provider.

This source base is no more maintained.
