### ISSUE TITLE
Force cockpit logout after install.sh

### ISSUE THREAD

**Issue by mareklibra** [oVirt/cockpit-machines-ovirt-provider#2]
The `root` user is required to run the plugin for the first time, since the install dialog will pop-up and the `install.sh` script will be executed to update cockpit's config files.

This procedure will be described within: https://github.com/mareklibra/cockpit-machines-ovirt-provider/issues/1

In the scope of this issue, force either Cockpit or the user to log out after successful `install.sh` is execution so the updated config files comes to effect.

**Comment by sandrobonazzola** [comment]
This project has been migrated under Cockpit, became base for cockpit-machines-provider.

This source base is no more maintained.
