### ISSUE TITLE
break long description into more lines

### ISSUE THREAD

**Issue by jelkosz** [oVirt/cockpit-machines-ovirt-provider#21]
the max length of a VM's description is 255 chars. If you do it, the UI looks like this:
![long-desc](https://cloud.githubusercontent.com/assets/701107/24711911/997d09ca-1a21-11e7-8113-56e418eb519a.png)
e.g. everything is pushed out of screen. I can still scroll there, but the ux suffers.

**Comment by sandrobonazzola** [comment]
This project has been migrated under Cockpit, became base for cockpit-machines-provider.

This source base is no more maintained.
