### ISSUE TITLE
Redundant items in Restart and Shutdown dropdowns

### ISSUE THREAD

**Issue by jniederm** [oVirt/cockpit-machines-ovirt-provider#24]
I found unnecessary to repeat the "Restart" and "Shutdown" option in dropdown menu. It just made me wonder whether there is some difference between them or not.

![image](https://cloud.githubusercontent.com/assets/5278760/25495260/d4434ea4-2b7c-11e7-9933-eba3b2bf15e1.png)

**Comment by mareklibra** [comment]
Fixed upstream: https://github.com/cockpit-project/cockpit/pull/6565
