### ISSUE TITLE
VM status visualization

### ISSUE THREAD

**Issue by jniederm** [oVirt/cockpit-machines-ovirt-provider#25]
I found it cleaner to user either only text (like Cockpit tab does) or only icons (probably with media control icon set).

Current state:
![vm-screenshot](https://cloud.githubusercontent.com/assets/5278760/25495664/3c945d4e-2b7e-11e7-91dc-d199e7524f9d.png)

Docker:
![docker-screenshot](https://cloud.githubusercontent.com/assets/5278760/25496156/329ef7fc-2b80-11e7-944e-c0dfbd50feb9.png)

**Comment by sandrobonazzola** [comment]
This project has been migrated under Cockpit, became base for cockpit-machines-provider.

This source base is no more maintained.
